Name:           wanfaild
Version:        0.03
Release:        1%{?dist}
Summary:        Monitor WAN links and provide failover
License:        GPL+
Group:          Development/Libraries
URL:            http://github.com/silug/wanfaild
Source0:        http://github.com/downloads/silug/wanfaild/wanfaild-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Pod) >= 1.00
BuildRequires:  perl(YAML::Tiny)
Requires:       perl(YAML::Tiny)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
wanfaild will monitor one or more WAN links and provide failover support.

%prep
%setup -q

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc COPYING README TODO
%{_bindir}/*
%{_mandir}/man1/*

%changelog
* Fri Apr 16 2010 Steven Pritchard <steve@kspei.com> 0.02-1
- Specfile autogenerated by cpanspec 1.79.
- Remove extra Test::* dependencies.
- Fix Source0 and URL.
- Fix files list to include bindir and man1.
